modLoader = "javafml"
loaderVersion = "[40.0,)"
issueTrackerURL = "https://github.com/MGSchultz-13/Evolution/issues/"
license = "GNU General Public License v3.0"
# A file name (in the root of the mod JAR) containing a logo for display
#logoFile="examplemod.png" #optional
[[mods]]
modId = "evolution"
version = "0.6.9"
displayName = "Evolution"
itemIcon = "evolution:debug_item"
# A URL to query for updates for this mod. See the JSON update specification <here>
#updateJSONURL="http://myurl.me/" #optional
displayURL = "https://github.com/MGSchultz-13/Evolution/"
#credits="Thanks for this example mod goes to Java" #optional
authors = "TheGreatWolf, loi777"
description = '''
Evolution is a mod for Minecraft that makes the game more realistic in many ways. Most features of the game have been completely remade from the ground up. As this mod is completely game changer, it is not recommended to be used with other mods. The mod is very early in its development and still is a Work in Progress. Expect bugs and unfinished features.
'''
[[dependencies.evolution]]
modId = "forge"
mandatory = true
versionRange = "[40.0,)"
ordering = "NONE"
side = "BOTH"
[[dependencies.evolution]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18.2]"
ordering = "NONE"
side = "BOTH"